services:
  web:
    image: truongikpk/bookstore-frontend:v1.0.0
    container_name: bookstore-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8080/api}
    networks:
      - bookstore-network
    restart: unless-stopped

networks:
  bookstore-network:
    external: true
    name: bookstore-network